{
  "hash": "59410b43c3007b16d982c10b117bce0f",
  "result": {
    "markdown": "---\ntitle: \"Error messages\"\nsubtitle: \"ggplot2 3.4.0\"\ncategories:\n   - \"ggplot2\"\nimage: \"ggplot-errors.png\"\nimage-alt: \"Text that says error messages ggplot2. An image of a line plot with lines of varying widths.\"\ndescription: \"ggplot2 3.4.0 has improved error messages when running plots.\"\ndate: 2022-11-04\n---\n\n\n\n\nInstall ggplot2 3.4.0 with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npak::pak(\"cran/ggplot2@3.4.0\")\n```\n:::\n\n\nLoad the package with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n### Better error messages\n\n...with better wording + cli package's rich text formatting!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(mtcars) |> \n  geom_point(aes(mpg, disp))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `geom_point()`:\n! `mapping` must be created by `aes()`\nℹ Did you use `%>%` or `|>` instead of `+`?\n```\n:::\n:::\n\n\nggplot2 error messages can be hard to diagnose because you get the error when you print the plot rather than when it happens in the code. This version tells you what the problem is, where it came from, and what to do about it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n\nmtcars |> \n  ggplot(aes(x = cyl, y = hp)) +\n  geom_bar()\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `geom_bar()`:\n! Problem while computing stat.\nℹ Error occurred in the 1st layer.\nCaused by error in `setup_params()`:\n! `stat_count()` must only have an x or y aesthetic.\n```\n:::\n:::\n\n\n## Learn more\n\n-   [tidyverse blog: ggplot 3.4.0](https://www.tidyverse.org/blog/2022/11/ggplot2-3-4-0/)\n-   [tidyverse release notes](https://ggplot2.tidyverse.org/news/index.html)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}